language: go
dist: focal
os: linux

go:
- "1.14.6"

services:
  - docker

branches:
  only:
    - master

# Install terraform
before_install:
  - docker run --name terraform -v ${PWD}:/workspace -w /workspace  --entrypoint /workspace/scripts/init.sh hashicorp/terraform:light 
  
jobs:
  include:
    - stage: terraform plan
      # Only run terraform validate and plan state if within a pull request
      if: type IN (pull_request)
      script:
        - echo "Executing Terraform Plan on pull request code"
        - docker run -e --name terraform -v ${PWD}:/workspace -w /workspace hashicorp/terraform:light plan ./confluent-cloud-deploy/dev/
    - stage: terraform apply
      # Only run terraform apply stage if outside of a pull request
      if: type IN (push) and branch = master
      script:
        - echo "Executing Terraform Apply on merged code"
        - docker run -e --name terraform -v ${PWD}:/workspace -w /workspace hashicorp/terraform:light apply ./confluent-cloud-deploy/dev/
