language: go
dist: focal
sudo: false

branches:
  only:
    - master

# Install terraform
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.8.8/terraform_0.8.8_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - env
  - export PATH="~/bin:$PATH"
  - curl https://raw.githubusercontent.com/sougat818/terraform-plugin-installer/master/install.sh | bash -s -- https://github.com/Mongey/terraform-provider-confluentcloud



script: terraform plan ./confluent-cloud-deploy/dev