FROM hashicorp/terraform:full

RUN apk add curl

RUN curl https://raw.githubusercontent.com/stavxyz/terraform-plugin-installer/master/install.sh | bash -s -- https://github.com/Mongey/terraform-provider-confluentcloud 17c01e8598f9c266efd1b8938d88b889a5d841ae